gym/gym/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('gym.profile_app.urls')),
    path('auth/', include('gym.auth_app.urls')),
    path('', include('gym.main_app.urls')),
    path('recipe/', include('gym.recipe_app.urls')),
    path('workout/', include('gym.workout_app.urls')),
]
handler404 = 'gym.main_app.views.handlers.error_404'
handler403 = 'gym.main_app.views.handlers.error_403'

gym/gym/main_app/models.py
from django.contrib.auth import get_user_model
from django.db import models

from gym.profile_app.models import ProfileModel

UserModel = get_user_model()


class GymInfoModel(models.Model):
    h1 = models.CharField(max_length=200)
    h1_span = models.CharField(max_length=20, null=False, blank=True)
    quote = models.CharField(max_length=250, null=False, blank=True)
    facebook_URL = models.URLField(null=False, blank=True)
    tweeter_URL = models.URLField(null=False, blank=True)
    instagram_URL = models.URLField(null=False, blank=True)
    working_time = models.TextField(null=False, blank=True)


class StarCoach(models.Model):
    owner = models.ForeignKey(ProfileModel, on_delete=models.CASCADE, related_name='star_owner')
    sender = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='star_sender')


class SearchModel(models.Model):
    search = models.CharField(max_length=50, verbose_name='Search')

gym/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gym site</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/7f59fdaec5.js" crossorigin="anonymous"></script>
    <script src="{% static 'scripts/script.js' %}" defer></script>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png">
</head>

<body>
<header>
    <nav class="navbar" style="width: 100%">
        <div class="brand-name"><a href="{% url 'index' %}">Pro<span>Athlete</span>Corner</a></div>
        <a href="#" class="toggle-button active">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </a>
        <div class="navbar-links" id="navigation">
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'trainers' %}" class="navbar-btn">Coaches</a></li>
                    <li><a href="{% url 'workout list' %}" class="navbar-btn">Workouts</a></li>
                    <li><a href="{% url 'list recipe' %}" class="navbar-btn">Recipes</a></li>
                    {% if user.has_profile %}
                        <li><a href="{% url 'profile page' user.id %}" class="navbar-btn">Profile</a></li>
                    {% else %}
                        <li><a href="{% url 'update profile' user.id %}" class="navbar-btn">Profile</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout' %}" class="navbar-btn">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'register' %}" class="navbar-btn">Register</a></li>
                    <li><a href="{% url 'login' %}" class="navbar-btn">Login</a></li>

                {% endif %}
            </ul>
        </div>
    </nav>
</header>


<main>

    {% block content %}

    {% endblock %}

</main>


<footer>

</footer>
</body>
</html>

gym/templates/coaches-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h1><i>A <span>COACH</span> turns a dreams to a reality!</i></h1>

    {% if object_list %}
        {% for coach in object_list %}
            <div class="box-card view-card">
                <a href="{% url 'profile page' coach.user_id %}">

                    <div class="card-title"><i class="fa-solid fa-star"></i></div>
                    <div class="card-img">
                        {% if coach.photo %}
                            <img src="{{ coach.photo.url }}" alt="my photo">
                        {% else %}
                               <img src="{% static 'images/generic_profile.png' %}" alt="my photo">
                        {% endif %}


                    </div>
                    <div class="card-text">
                        <h2>
                            {{ coach.full_name }}
                        </h2>
                        <br>
                        <p>{{ coach.description | truncatewords:35 }} </p>
                        {% if coach.crossfit_coach %}
                            <h4>
                            <span>
                                <i class="fa-solid fa-hand-point-right"></i>
                                <span style="color: #ECECEC">CrossFIt</span>
                            </span>
                            </h4>
                        {% endif %}
                        {% if coach.fitness_coach %}
                            <h4>
                            <span>
                                <i class="fa-solid fa-hand-point-right"></i>
                                <span style="color: #ECECEC">Fitness</span>
                            </span>
                            </h4>
                        {% endif %}
                        {% if coach.combat_coach %}
                            <h4>
                            <span>
                                <i class="fa-solid fa-hand-point-right"></i>
                                <span style="color: #ECECEC">Combat</span>
                            </span>
                            </h4>
                        {% endif %}
                        {% if coach.yoga_coach %}
                            <h4>
                            <span>
                                <i class="fa-solid fa-hand-point-right"></i>
                                <span style="color: #ECECEC">Yoga</span>
                            </span>
                            </h4>
                        {% endif %}
                        {% if coach.dance_coach %}
                            <h4>
                            <span>
                                <i class="fa-solid fa-hand-point-right"></i>
                                <span style="color: #ECECEC">Dance</span>
                            </span>
                            </h4>
                        {% endif %}

                    </div>
                    <div class="card-footer">
                        <div class="card-bottom-half border">
                            <a href="{% url 'coach workouts' coach.pk %}">
                                <div class="value">
                                    <i class="fa-solid fa-dumbbell"></i>
                                </div>
                                <div class="type">TRAIN WITH ME</div>
                            </a>
                        </div>

                        <div class="card-bottom-half">
                            <a href="{% url 'star the coach' coach.pk %}">
                                <div class="value">
                                    {% if coach.is_stars_by_the_user %}
                                        <i class="fa-solid fa-star" style="color: #ECECEC"></i>
                                        <div class="type"> Thank you</div>
                                    {% else %}
                                        <i class="fa-solid fa-star"></i>
                                        <div class="type">GIV ME A STAR</div>
                                    {% endif %}
                                </div>
                            </a>

                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}

        <div class="pagination comment center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>
    {% else %}
        <h1>We are looking for the best coaches.</h1>
    {% endif %}


{% endblock %}

gym/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h1><i>Push through the pain <span>EVERY</span> single day?</i></h1>
    <section class="about">

        <form action="{% url 'search' %}" method="post" class="center">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" name="search" id="id_search" style="border-radius: 20px; width: 60%;">
                <input type="submit" style="border-radius: 20px; width:20%;" value="Search">
            </div>


        </form>
        <h2>{{ is_true }}</h2>
        <div class="comment center">
            <i class="fa-solid fa-quote-right"></i>
            <p>“The human body has been designed to resist an infinite number of changes and attacks brought about by
                its environment. The secret of good health lies in successful adjustment to changing stresses on the
                body.” – Harry J. Johnson</p>
            <br><br>
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <a href="#" class="button-register" style="width: 40px">Update Site</a>
                {% endif %}
                {% if user.has_profile %}
                    <a href="{% url 'profile page' user.id %}" class="button-register" style="width: 40px">Profile
                        Page</a>
                {% else %}
                    <a href="{% url 'update profile' user.id %}" class="button-register" style="width: 40px">Profile
                        Page</a>
                {% endif %}

            {% else %}
                <a href="{% url 'register' %}" class="button-register" style="width: 40px">Register</a>
                <a href="{% url 'login' %}" class="button-register" style="width: 40px">Login</a>
            {% endif %}
        </div>
    </section>

{% endblock %}

gym/templates/new_navigation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gym site</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/7f59fdaec5.js" crossorigin="anonymous"></script>
    <script src="{% static 'scripts/script.js' %}" defer></script>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png">
</head>

<body>
<header>
    <nav class="navbar" style="width: 100%">
        <div class="brand-name"><a href="{% url 'index' %}">Pro<span>Athlete</span>Corner</a></div>
        <a href="#" class="toggle-button active">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </a>
        <div class="navbar-links" id="navigation">
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="#" class="navbar-btn">Coaches</a></li>
                    <li><a href="#" class="navbar-btn">Camps</a></li>
                    <li><a href="#" class="navbar-btn">Workouts</a></li>
                    <li><a href="{% url 'list recipe' %}" class="navbar-btn">Recipes</a></li>
                    <li><a href="{% url 'profile page' user.id %}" class="navbar-btn">Profile</a></li>
                    <li><a href="{% url 'logout' %}" class="navbar-btn">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'register' %}" class="navbar-btn">Register</a></li>

                {% endif %}

            </ul>
        </div>
    </nav>
</header>


<main>

    {% block content %}

    {% endblock %}

</main>


<footer>
    <section id="social">
        <div class="contacts">
            <ul>
                <li class="fa-icon">
                    <i class="fa fa-facebook-square" aria-hidden="true"></i>
                </li>
                <li class="fa-icon">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                </li>
                <li class="fa-icon">
                    <i class="fa fa-twitter-square" aria-hidden="true"></i>
                </li>
                <li class="fa-icon">
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                </li>
            </ul>
        </div>
    </section>
    <div id="info"><h1>Work time</h1></div>
    <div id="links">
        <div class="footer-links">
            <ul>
                <li><a href="#">About</a></li>
                <li><a href="#">Coaches</a></li>
                <li><a href="#">Workouts</a></li>
                <li><a href="#">Camps</a></li>
                <li><a href="#">Recipes</a></li>
            </ul>
        </div>
    </div>
    <div id="map"><img src="https://www.w3schools.com/w3images/map.jpg" alt="map"></div>
    <div id="bottom"><p>&copy; Copyright 2022 ProAthleteCorner Team. All rights reserved.</p></div>
</footer>
</body>
</html>

gym/templates/searched-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="comment center">
        {% if no_matches %}
            <h1>{{ no_matches }}</h1>
    {% else %}

            {% if workouts %}
                <h1>WORKOUTS</h1>
                {% for workout in workouts %}
                    <a href="{% url 'workout details' workout.pk %}">
                        <div class="comment center">
                            <h2>{{ workout.title }}</h2>
                            <h3>{{ workout.type_of_workout }}</h3>
                            <p>{{ workout.date }} at {{ workout.hour }}</p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}

            {% if recipes %}
                <h1>RECIPES</h1>
                {% for recipe in recipes %}
                    <a href="{% url 'details recipe' recipe.pk %}">
                        <div class="comment center">
                            <h2>{{ recipe.title }}</h2>
                            <h3>{{ recipe.author }}</h3>
                            <p>{{ recipe.description | truncatewords:20 }}</p>
                        </div>
                    </a>
                    <br>
                {% endfor %}
            {% endif %}

            {% if coaches %}
                <h1>COACHES</h1>
                {% for trener in coaches %}
                    <a href="{% url 'profile page' trener.pk %}">
                        <div class="comment center">
                            <h2>{{ trener.full_name }}</h2>
                            <h3>{{ trener.gender }}</h3>
                            <p>{{ trener.description | truncatewords:20 }}</p>
                        </div>
                    </a>
                    <br>
                {% endfor %}
            {% endif %}
    {% endif %}

        <br>

    <p><a href="{% url 'index' %}" class="button-register center" style="width: 40px">BACK</a></p>
    </div>


{% endblock %}